# Generated by Django 3.2.5 on 2021-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210811_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Featured_Product',
        ),
    ]
