# Generated by Django 3.2.5 on 2021-08-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210812_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
